### ISSUE TITLE
Overriding remote Ollama URL and throwing error.

### ISSUE THREAD

**Issue by clickbrain** [RetricSu/sisyphus#40]
I run ollama on a remote server. I put that URL into base.toml. In example below, I have changed the url, because I don't want to expose my true url, but I have this remote server working fine with a dozen other AI tools and platforms. 

[llm]
apiUrl = 'https://ollamasub.mydomain.com'
model = 'llma3.2'
provider = 'ollama'

When I run sisyphus, I get the You: prompt, but they it throws the error below, which seems to indicate, that the standard Ollama local URL is overriding what I put in base.toml. 

(sis) bradn@Brads-MacBook-Pro sisyphus % sisyphus chat --prompt base
[debug]: Init a New Privkey for Agent base
(node:13776) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
>>> You: What can we create together?
----
>>> Sisyphus: [error]: some thing went wrong...
RetryError [AI_RetryError]: Failed after 3 attempts. Last error: Cannot connect to API: connect ECONNREFUSED 127.0.0.1:11434
    at _retryWithExponentialBackoff (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:346:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fn (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:3671:32)
    at async /Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:533:22 {
  cause: undefined,
  reason: 'maxRetriesExceeded',
  errors: [
    APICallError [AI_APICallError]: Cannot connect to API: connect ECONNREFUSED 127.0.0.1:11434
        at postToApi (/Users/bradn/Library/pnpm/global/5/.pnpm/@ai-sdk+provider-utils@2.0.5_zod@3.24.1/node_modules/@ai-sdk/provider-utils/dist/index.js:456:15)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async OllamaChatLanguageModel.doGenerate (/Users/bradn/Library/pnpm/global/5/.pnpm/ollama-ai-provider@1.1.0_zod@3.24.1/node_modules/ollama-ai-provider/dist/index.js:503:50)
        at async fn (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:3711:30)
        at async /Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:533:22
        at async _retryWithExponentialBackoff (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:334:12)
        at async fn (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:3671:32)
        at async /Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:533:22 {
      cause: [Error],
      url: 'http://127.0.0.1:11434/api/chat',
      requestBodyValues: [Object],
      statusCode: undefined,
      responseHeaders: undefined,
      responseBody: undefined,
      isRetryable: true,
      data: undefined,
      [Symbol(vercel.ai.error)]: true,
      [Symbol(vercel.ai.error.AI_APICallError)]: true
    },
    APICallError [AI_APICallError]: Cannot connect to API: connect ECONNREFUSED 127.0.0.1:11434
        at postToApi (/Users/bradn/Library/pnpm/global/5/.pnpm/@ai-sdk+provider-utils@2.0.5_zod@3.24.1/node_modules/@ai-sdk/provider-utils/dist/index.js:456:15)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async OllamaChatLanguageModel.doGenerate (/Users/bradn/Library/pnpm/global/5/.pnpm/ollama-ai-provider@1.1.0_zod@3.24.1/node_modules/ollama-ai-provider/dist/index.js:503:50)
        at async fn (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:3711:30)
        at async /Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:533:22
        at async _retryWithExponentialBackoff (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:334:12)
        at async fn (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:3671:32)
        at async /Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:533:22 {
      cause: [Error],
      url: 'http://127.0.0.1:11434/api/chat',
      requestBodyValues: [Object],
      statusCode: undefined,
      responseHeaders: undefined,
      responseBody: undefined,
      isRetryable: true,
      data: undefined,
      [Symbol(vercel.ai.error)]: true,
      [Symbol(vercel.ai.error.AI_APICallError)]: true
    },
    APICallError [AI_APICallError]: Cannot connect to API: connect ECONNREFUSED 127.0.0.1:11434
        at postToApi (/Users/bradn/Library/pnpm/global/5/.pnpm/@ai-sdk+provider-utils@2.0.5_zod@3.24.1/node_modules/@ai-sdk/provider-utils/dist/index.js:456:15)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async OllamaChatLanguageModel.doGenerate (/Users/bradn/Library/pnpm/global/5/.pnpm/ollama-ai-provider@1.1.0_zod@3.24.1/node_modules/ollama-ai-provider/dist/index.js:503:50)
        at async fn (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:3711:30)
        at async /Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:533:22
        at async _retryWithExponentialBackoff (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:334:12)
        at async fn (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:3671:32)
        at async /Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:533:22 {
      cause: [Error],
      url: 'http://127.0.0.1:11434/api/chat',
      requestBodyValues: [Object],
      statusCode: undefined,
      responseHeaders: undefined,
      responseBody: undefined,
      isRetryable: true,
      data: undefined,
      [Symbol(vercel.ai.error)]: true,
      [Symbol(vercel.ai.error.AI_APICallError)]: true
    }
  ],
  lastError: APICallError [AI_APICallError]: Cannot connect to API: connect ECONNREFUSED 127.0.0.1:11434
      at postToApi (/Users/bradn/Library/pnpm/global/5/.pnpm/@ai-sdk+provider-utils@2.0.5_zod@3.24.1/node_modules/@ai-sdk/provider-utils/dist/index.js:456:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async OllamaChatLanguageModel.doGenerate (/Users/bradn/Library/pnpm/global/5/.pnpm/ollama-ai-provider@1.1.0_zod@3.24.1/node_modules/ollama-ai-provider/dist/index.js:503:50)
      at async fn (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:3711:30)
      at async /Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:533:22
      at async _retryWithExponentialBackoff (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:334:12)
      at async fn (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:3671:32)
      at async /Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:533:22 {
    cause: Error: connect ECONNREFUSED 127.0.0.1:11434
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 11434
    },
    url: 'http://127.0.0.1:11434/api/chat',
    requestBodyValues: {
      format: undefined,
      model: 'llama3.1',
      options: [Object],
      messages: [Array],
      tools: [Array],
      stream: false
    },
    statusCode: undefined,
    responseHeaders: undefined,
    responseBody: undefined,
    isRetryable: true,
    data: undefined,
    [Symbol(vercel.ai.error)]: true,
    [Symbol(vercel.ai.error.AI_APICallError)]: true
  },
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_RetryError)]: true

**Comment by RetricSu** [comment]
@clickbrain  please make sure the `base.toml` you edit is the real one, not the predefined one in the source code. You can check out the real one by running:

```sh
sisyphus config list
```

and see the root folder of the prompt:

```sh
prompt: {
    rootFolder: '<path-to-prompt-root-folder>',
  },
```

the `base.toml` is at `<path-to-prompt-root-folder>/base.toml`

**Comment by clickbrain** [comment]
OK, did that and edited the correct one and it looks like the system is adding /chat to the endpoint URL instead of just accepting the URL as it is. I've edited the base URL in the error below, but you can see where the app added /chat to the endpoint. 

(sis) bradn@Brads-MacBook-Pro sisyphus % sisyphus chat --prompt base
(node:14302) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
>>> You: WHat can we create together?
----
>>> Sisyphus: [error]: some thing went wrong...
APICallError [AI_APICallError]: Not Found
    at /Users/bradn/Library/pnpm/global/5/.pnpm/@ai-sdk+provider-utils@2.0.5_zod@3.24.1/node_modules/@ai-sdk/provider-utils/dist/index.js:523:14
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async postToApi (/Users/bradn/Library/pnpm/global/5/.pnpm/@ai-sdk+provider-utils@2.0.5_zod@3.24.1/node_modules/@ai-sdk/provider-utils/dist/index.js:408:28)
    at async OllamaChatLanguageModel.doGenerate (/Users/bradn/Library/pnpm/global/5/.pnpm/ollama-ai-provider@1.1.0_zod@3.24.1/node_modules/ollama-ai-provider/dist/index.js:503:50)
    at async fn (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:3711:30)
    at async /Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:533:22
    at async _retryWithExponentialBackoff (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:334:12)
    at async fn (/Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:3671:32)
    at async /Users/bradn/Library/pnpm/global/5/.pnpm/ai@4.0.22_react@18.3.1_zod@3.24.1/node_modules/ai/dist/index.js:533:22 {
  cause: undefined,
  url: 'https://ollamasub.mydomain.com/chat',
  requestBodyValues: {
    format: undefined,
    model: 'hermes3',
    options: { temperature: 0 },
    messages: [ [Object], [Object] ],
    tools: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    stream: false
  },
  statusCode: 404,
  responseHeaders: {
    'content-length': '18',
    'content-type': 'text/plain',
    date: 'Mon, 23 Dec 2024 02:03:16 GMT'
  },
  responseBody: '404 page not found',
  isRetryable: false,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true

**Comment by clickbrain** [comment]
Thank you for your help by the way.

**Comment by clickbrain** [comment]
Thank you for your help by the way. Really like the idea of what you've created here.

**Comment by RetricSu** [comment]
Since for the lcoal host:

```toml
[llm]
apiUrl = 'http://127.0.0.1:11434/api'
model = 'llama3.1'
provider = 'ollama'
```
@clickbrain Maybe try pass `'https://ollamasub.mydomain.com/api` ?

**Comment by RetricSu** [comment]
> Thank you for your help by the way. Really like the idea of what you've created here.

thx for your feedback too, not many people use this now but i am trying to make it better.

**Comment by clickbrain** [comment]
That worked! Thanks. 

I will play with this some more in the next few days and try to come back with some good feedback.
